CONFIG_ZMK_KEYBOARD_NAME="Sofle choc"
# ADD support zmk studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
# ADD support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# ADD support backlight
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
## ADD auto off
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
# ADD support display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
## Display config
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n
### Peripheral
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
### Center
CONFIG_NICE_OLED_WIDGET_WPM=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_LAYER=y
CONFIG_NICE_OLED_WIDGET_CENTRAL=y
# ADD battery level
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# Power management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
# BT
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Split
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y