manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      ####
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: stelmakhdigital
      url-base: https://github.com/stelmakhdigital
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
      ####
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    - name: zmk_driver_azoteq
      remote: stelmakhdigital
      revision: master
  self:
    path: config
